### ISSUE TITLE
ImportError: cannot import name 'Game' from 'chess' 

### ISSUE THREAD

**Issue by suzyrhkr** [ImparaAI/monte-carlo-tree-search#12]
As written in your README.md "Usage",
I want to create Montecarlo Tree, but I cannot import Game().

Can you tell me **specific version of chess** that you used in your code?
I installed chess with this command "pip install python-chess"

**from chess import Game**
from montecarlo.node import Node
from montecarlo.montecarlo import MonteCarlo

**chess_game = Game()**

**Comment by sdsomma** [comment]
This repo is used with https://github.com/ImparaAI/checkers which has the Game class

**Comment by janhartigan** [comment]
@suzyrhkr just FYI, it says this in the docs right after that code snippet:

> For the sake of demonstration, we will assume you have a generic Game library that can tell you what moves are possible and allows you to perform those moves to change the game's state.

The point of that import is to show that the MCTS doesn't care what value is passed into the `Node` constructor, just that it represents some state value of that particular node in the tree. It could be an integer, a string, or a complex `Game` state object as shown in the readme.
